[k8s_master]
3.145.18.135 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ec2-user/project-2/ansible/bee.pem

[k8s_worker]
18.225.36.206 ansible_user=ubuntu ansible_ssh_private_key_file=/home/ec2-user/project-2/ansible/bee.pem
